Setup database
dannehdan/speedaisle pull request #6
Opened 2021-11-16 14:54 UTC by pzrsa

2021-11-16 15:24 UTC, pzrsa commented
so i've looked at trying to have the default values set for the categories (like household or fridge) and it seems like i cant do that with Prisma. what we could do is set those values when the list is created, we can talk more about this later when the time comes for generating a list.

2021-11-16 16:33 UTC, frontendowl requested changes
Great job, but, please, add a column for category_id to the Items table.
What would we store in the order_id column of Category table?

2021-11-16 16:33 UTC, frontendowl commented on prisma/schema.prisma
> +  listId Int
we need category_id column as well

2021-11-16 16:33 UTC, frontendowl commented on prisma/schema.prisma
> +  orderId Int
why do we need orderId column here?

2021-11-17 10:42 UTC, frontendowl approved these changes

2021-11-17 10:42 UTC, merged